apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wbzeoerto-python
  janus-idp.io/tekton: wbzeoerto-python
  backstage.io/kubernetes-id: wbzeoerto-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wbzeoerto-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
